"use client"
import Header from "@/app/components/Header"
import "./global.css"
import FirebaseProvider from "./provider/FirebaseProvider"

export const metadata = {
  title: 'Home',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Golos+Text&family=PT+Sans&family=Roboto+Slab&family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet" />   
        <main>
          <FirebaseProvider>
            <Header />
            {children}
          </FirebaseProvider>
          
        </main>
      </body>
    </html>
  )
}
